name: MooStarRating
author: lorenzo.stanco
category: Interface
tags: [star, rating, radio, form]
demo: http://jsfiddle.net/UJJN7/438/
docs: http://wiki.github.com/lorenzos/MooStarRating/docs
current: 1.4
sources:
  - Source/moostarrating.js
